### ISSUE TITLE
does not work on Samsung Touchwiz Oreo ROM

### ISSUE THREAD

**Issue by kamilmirza** [Magisk-Modules-Repo/dns_switch#3]
when `dns_switch` typed in terminal it stats:

`dns_switch
/system/xbin/dns_switch[134]: log_handler: not found
/system/xbin/dns_switch[140]: log_handler: not found
/system/xbin/dns_switch[196]: get_file_value: not found
/system/xbin/dns_switch[197]: get_file_value: not found
/system/xbin/dns_switch[575]: syntax error: '}' unexpected`

**Comment by KeisariJulma** [comment]
Having same issue with LineageOS 14.1 on Elephone P9000 with Magisk 19.1v

**Comment by renesmeee** [comment]
Same here

**Comment by retakal** [comment]
Same issue here:
lineageOS 14.1 on redmi 3 (ido) with Magisk v19.1

**Comment by DRD1N0** [comment]
Same here on pixel 3a on Pie - Magisk 19

**Comment by JohnFawkes** [comment]
Fixed in 45d262f7e6f8213ab76d007bc7567b5d341c6ae2
