### ISSUE TITLE
Can't create /cache/DNSSwitch-verbose.log: Read-only file system

### ISSUE THREAD

**Issue by nii-nii** [Magisk-Modules-Repo/dns_switch#4]
As mentioned above, I get a error when I'm trying to use the DNS switch.

I'm root and I'm doing this in a terminal by running su.

A [picture ](https://imgur.com/a/bnVQBJZ)is attached to reflect the issue.

**Comment by KeisariJulma** [comment]
Try remounting cache as rewritable:
     `su`
     `mount -o rw,remount /cache`
and if you want it back to read only:
     `mount -o ro,remount /cache`

**Comment by JohnFawkes** [comment]
Fixed in 45d262f7e6f8213ab76d007bc7567b5d341c6ae2
