### ISSUE TITLE
logging.sh not found

### ISSUE THREAD

**Issue by jdlothar** [Magisk-Modules-Repo/dns_switch#6]
=============
$ su
angler:/data/data/com.termux/files/home #
angler:/data/data/com.termux/files/home # dns_switch
/system/xbin/dns_switch[20]: .: /data/adb/modules/dns_switch/logging.sh: No such file or directory
1|angler:/data/data/com.termux/files/home #
==============

Installed today from Magisk.
Magisk 19.2
Magisk Manager 7.2.0 (213)
DNS Switcher v7
Busybox for Android NDK 1.30.1

Nexus 6p
Android 8.1
LineageOS 15.1.20190507-NIGHTLY-angler

**Comment by crok** [comment]
Hi,

This is the same issue I reported in issue #5 7 days ago.

**Comment by jdlothar** [comment]
@crok Read yours before I submitted mine.  Your error message says the file could not be created and my error was not found.  Might be two different error conditions and figured more info is better.

**Comment by crok** [comment]
It seems to be fixed in v8. I recommend you to check it again and close the issue.

**Comment by jdlothar** [comment]
Upgraded to version 9 and got a new error
/system/xbin/dns_switch[20]: can't create : No such file or directory

Removed module, reboot, verified /system/xbin/dns_switch removed

Added module back, reboot.  Same error.

**Comment by JohnFawkes** [comment]
Fixed in 45d262f7e6f8213ab76d007bc7567b5d341c6ae2
