### ISSUE TITLE
[BUG] Invalid 'log_start' command

### ISSUE THREAD

**Issue by jdhedden** [Magisk-Modules-Repo/dns_switch#7]
When I run the 'dns_switch' command, the following output occurs:

/system/xbin/dns_switch[20]: can't create : Not such file or directory

This is caused by the following line in the 'dns_switch' script:

log_start "Running Log script." >> $LOG 2>&1

The error is cause because the variable LOG is not yet defined.   It is not defined until line 49.

**Comment by JohnFawkes** [comment]
Fixed in 45d262f7e6f8213ab76d007bc7567b5d341c6ae2
