### ISSUE TITLE
[BUG] "dns_switch -l" does not provide any output

### ISSUE THREAD

**Issue by jdhedden** [Magisk-Modules-Repo/dns_switch#8]
Running 'dns_switch -l' does not provide any output:

OnePlus7Pro@android:/ # dns_switch -l
/system/xbin/dns_switch[20]: can't create : No such file or directory
OnePlus7Pro@android:/ #

(The above error does not stop the script from functioning, and I have reported it under a different bug report.)

**Comment by jdhedden** [comment]
The issue is in the code:

-l|-L) shift
  for i in "$@"; do
custom=$(echo $(get_file_value $DNSLOG "custom=") | sed 's|-.*||')
custom2=$(echo $(get_file_value $DNSLOG "custom2=") | sed 's|-.*||')
  if [ "$custom" ]; then
  echo -e "${W}Your Custom DNS is :${N} ${R}$custom${N}"
  elif [ "$custom2" ]; then
  echo -e "${W}Your Second Custom DNS is :${N} ${R}$custom2${N}"
  else
  echo -e "${R}NO CUSTOM DNS IN USE${N}"
  echo -e "${R}Please run 'su' then 'dns_switch' to use a custom DNS${N}"
  fi
  done
  exit;;

The above is 'requiring' a command line argument which is unnecessary.  I recommend the following rewrite:

-l|-L)
  custom=$(echo $(get_file_value $DNSLOG "custom=") | sed 's|-.*||')
  custom2=$(echo $(get_file_value $DNSLOG "custom2=") | sed 's|-.*||')
  if [ "$custom" ]; then
    echo -e "${W}Your Custom DNS is :${N} ${R}$custom${N}"
    if [ "$custom2" ]; then
      echo -e "${W}Your Second Custom DNS is :${N} ${R}$custom2${N}"
    if
  elif [ "$custom2" ]; then
    echo -e "${W}Your Second Custom DNS is :${N} ${R}$custom2${N}"
  else
    echo -e "${R}NO CUSTOM DNS IN USE${N}"
    echo -e "${R}Please run 'su' then 'dns_switch' to use a custom DNS${N}"
  fi
  exit;;

**Comment by JohnFawkes** [comment]
Thanks. Sorry I haven't had time to update dns switch. Ive got some time from school and work so will be updating the module very soon

**Comment by JohnFawkes** [comment]
Fixed in 45d262f7e6f8213ab76d007bc7567b5d341c6ae2
